### ISSUE TITLE
When sing navigation buttons while reading (not paused) delay is too long

### ISSUE THREAD

**Issue by kabamot** [kabamot/Zyrlo#4]
When paused Next/ Prev word is working fine. When unpaused, the delay between pressing the button ad reading prev/next word is too high.  Same for next/prev sentence

**Comment by dilshodm** [comment]
I put it to 1s. I'm going to put one control where you can set value in ms and choose which one feels good. Then we will hard-code it

**Comment by dilshodm** [comment]
Please, check [test_delay](https://github.com/kabamot/Zyrlo/tree/test_delay) temporary branch where you can set the value and advice which value we can use.

**Comment by dilshodm** [comment]
Improved word navigation implemented: immediately read the word and wait for the next button or continue page reading with delay

**Comment by kabamot** [comment]
Hi Dilshod,

Here is a label. I also attached a center of the label that camera is looking for. But I think it may be more complicated then just placing a picture. It keeps a low resolution image, and searching for it in the camera image. If height (distance to the camera) is a little different, it will not do any scaling, and therefore will not find it. Also, it may look different on a different paper.
